### ISSUE TITLE
What's the license for this repository?

### ISSUE THREAD

**Issue by aroben** [jlfwong/speedscope#10]
What's the license for this repository? I don't see it in the README or in the repo.

It'd be great to add a LICENSE file to the repository to make this clear.

This project looks really nice!

**Comment by jlfwong** [comment]
I intend for it to be MIT licensed, I just haven't added the actual file yet :)

I'll leave this issue open until I do.

**Comment by jlfwong** [comment]
Fixed by 298056a9ef35187a6e3ca02196b651ad2337e53d. Thanks for the prod!
