### ISSUE TITLE
Support Windows line endings (CRLF) in Brendan Gregg's collapsed stack format text files

### ISSUE THREAD

**Issue by januszn** [jlfwong/speedscope#152]
It seems that the app chokes on text files with Windows line endings, with the generic "Unrecognized format! See documentation about supported formats." error popup. Unless it's deliberate, JWZ-style (https://www.jwz.org/xscreensaver/xscreensaver-windows.html), the support would spare Windows users the extra step of converting the line endings to LF.
[collapsed-stacks-with-crlf.txt](https://github.com/jlfwong/speedscope/files/2315968/collapsed-stacks-with-crlf.txt)
[collapsed-stacks-with-lf.txt](https://github.com/jlfwong/speedscope/files/2315969/collapsed-stacks-with-lf.txt)

**Comment by jlfwong** [comment]
That's probably this code right here: https://github.com/jlfwong/speedscope/blob/828beb7ccf329ad3d3f6821ea53e577621ec6432/src/import/index.ts#L106

Would be happy to accept a patch to fix this! Check out [CONTRIBUTING.md](https://github.com/jlfwong/speedscope/blob/master/CONTRIBUTING.md) if you'd like to give this a shot! It might be only a few characters to fix it.
