### ISSUE TITLE
Chrome 69 CPU profile format seems to have changed

### ISSUE THREAD

**Issue by jyc** [jlfwong/speedscope#159]
With a CPU profile generated by Chrome 69, import fails with "Could not find CPU profile in Timeline". It looks like Chrome has changed their output format. The only event that now has an `args.data.cpuProfile` value has the name `ProfileChunk`, but there seem to be a lot of them and they don't have a `startTIme` or `endTime` and instead of the nodes having a list of children, they now identify their parent, among lots of other changes.

**Comment by jyc** [comment]
It looks like this commit renamed `CpuProfile` to `Profile`: https://chromiumcodereview.appspot.com/2425093002

I am not sure why the `Profile` event has no `endTime`, though.

```
→ jq '.[] | select(.name == "Profile")'< ~/Downloads/long-profile           
{
  "pid": 1897,
  "tid": 775,
  "ts": 11598805128,
  "ph": "P",
  "cat": "disabled-by-default-v8.cpu_profiler",
  "name": "Profile",
  "args": {
    "data": {
      "startTime": 11598805078
    }
  },
  "tts": 149064668,
  "id": "0x3"
}
```

I wonder if this event is supposed to have an `args.data.cpuProfile` value too.

**Comment by jyc** [comment]
Might be a bug in Chrome? Profiles on two different computers both have a seemingly half-finished `Profile` event like the one above. From the code, it looks like if the profile were finished, we would at least expect an `endTime` event: https://cs.chromium.org/chromium/src/v8/src/profiler/profile-generator.cc?q=cpuProfile&sq=package:chromium&dr=CSs&l=504

**Comment by jlfwong** [comment]
@jyc Thanks for doing the research! I'll dig in and see what I can find
