### ISSUE TITLE
Importing from XCode 10.0 Instruments fails

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#163]
The code to import from instruments was tested against Xcode 8 & 9, but it seems like something in 10 broke it.

**Comment by jlfwong** [comment]
@aparrapo I don't intend to install Xcode 10 at the moment, but if you'd like to help this process along, you can record a simple trace of a test program in this respository using Instruments.

To do that, clone this repository then do:

```
cd sample/programs/cpp
make simple
./simple
```

Then find that process in Instruments and record a time profile of it. If you could do that and send the file, then that would accelerate this process since I don't have Xcode 10 installed & don't want to mess up my dev environment.

**Comment by aparrapo** [comment]
There you go :)
[Instruments_sample.trace.zip](https://github.com/jlfwong/speedscope/files/2383994/Instruments_sample.trace.zip)

I tested this trace and I get the same message, so it should be good for debugging purposes.

**Comment by jlfwong** [comment]
@aparrapo Thanks! 😄

I probably won't get to this in the next week or so, but I'll try to find some time to take a look. If you are interested in contributing, I did a writeup of how I dug around these files in the past: http://jamie-wong.com/post/reverse-engineering-instruments-file-format/

Let me know if you're interested in taking this on yourself, otherwise it might take a while, though certainly not as long as if I had to upgrade Xcode 🙂

**Comment by jlfwong** [comment]
Hi @aparrapo I just unzipped `Insturments_sample.trace.zip` that you attached and I was able to import the contents into https://www.speedscope.app/. I also tried generating a multithreaded profile recording my copy of Visual Studio Code or 30 seconds, and that was able to import as well.

![image](https://user-images.githubusercontent.com/150329/46426369-3ac2d600-c6f3-11e8-8947-74d8d63b3145.png)

I'm going to close this for now since I can't reproduce the problem. If you are able to create a small example of a profile that won't import, please let me know!
