### ISSUE TITLE
Format support: Google's pprof

### ISSUE THREAD

**Issue by divan** [jlfwong/speedscope#164]
There is Google protobuf-based file format used for profilers in Google tooling. I'm more interested in being able to open profiles for Go programs, generated by built-in `go tool pprof`.

https://github.com/google/pprof/tree/master/proto
https://blog.golang.org/profiling-go-programs

I've seen the [mention](https://github.com/jlfwong/speedscope/issues/18#issuecomment-419660807) of charity donations based policy for selecting issues. Would it apply here?

**Comment by jlfwong** [comment]
Hi @divan!

I believe this is the same as https://github.com/jlfwong/speedscope/issues/60. The charity donation policy applies there, since the comment is on that thread!

**Comment by divan** [comment]
Oh, missed that. Thanks!
