### ISSUE TITLE
Crash when importing a speedscope.json file containing no profiles

### ISSUE THREAD

**Issue by janpio** [jlfwong/speedscope#169]
I created a file for speedscope with `rbspy`:
`rbspy record --format speedscope -- ruby c:\Ruby24-x64\bin\bundle exec fastlane -v`

The results can't be parsed unfortunately:
![image](https://user-images.githubusercontent.com/183673/46179432-7573db00-c2bb-11e8-96ce-118e243b8ccc.png)

Same result on https://www.speedscope.app/ and with local install via `npm install -g speedscope`.

[rbspy-2018-09-27-SDdIvd06Wl.speedscope.json.zip](https://github.com/jlfwong/speedscope/files/2426184/rbspy-2018-09-27-SDdIvd06Wl.speedscope.json.zip)

**Comment by jlfwong** [comment]
Sounds like a bug to me! I'll try to take a look sometime in the next week or so

**Comment by janpio** [comment]
Probably important information: I created the file with `rbspy` on Windows - can very well be that it doesn't work properly or is untested there as well.

**Comment by jlfwong** [comment]
Hmm. I was just able to import the attached file by unzipping the file and dragging the result into https://www.speedscope.app/

![image](https://user-images.githubusercontent.com/150329/46181426-8c460d80-c27a-11e8-9837-f0cb4595e7a1.png)

**Comment by jlfwong** [comment]
I'm going to close this for now since it seems like the import is working correctly for me. Let me know if you think this is e.g. Windows specific somehow.

**Comment by jlfwong** [comment]
Ahh, I see! Thanks, yes, that is definitely a bug. We shouldn't crash when getting a file with no profiles in it.
