### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by gedw99** [jlfwong/speedscope#174]
Is is possible to add a command to change the font size ?

The zoom function does not do it.

**Comment by jlfwong** [comment]
Hi @gedw99!

If you select the location bar in Chrome, then hit Cmd+ (or Ctrl+ on Linux/Windows), it should effectively increase the font size.

Here's a screenshot where I've done that, and you should be able to do it too.

![image](https://user-images.githubusercontent.com/150329/46596775-81695500-ca92-11e8-9a8d-0b35cc3569d1.png)

Let me know if that doesn't work for you, or if I've misunderstood the issue.
