### ISSUE TITLE
Format Support: Callgrind

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#18]
https://kcachegrind.github.io/html/CallgrindFormat.html

This is also a common format output by some other profiles, like XDebug for PHP (https://xdebug.org/docs/profiler)

**Comment by jlfwong** [comment]
I’ll commit to implementing this feature myself if a total of $200 of donations is made to any combination of these specific charities:

- [American Civil Liberties Union](https://www.aclu.org/)
- [/dev/color](https://www.devcolor.org/welcome): /dev/color is a non-profit organization whose mission is to empower Black software engineers to help one another grow into industry leaders.
- [Girls Who Code](https://girlswhocode.com/about-us/): Girls Who Code was founded with a single mission: to close the gender gap in technology

If you’d like to contribute to that total, please post a screenshot of your donation receipt in this thread*.

Independent of that, I would accept a PR to implement this, regardless of donation amounts.

*: I'm planning on trying this policy on a number of issues. Donations will apply to the total of exactly one issue, so please don't post the same receipt in multiple issue threads.

**Comment by titpetric** [comment]
![image](https://user-images.githubusercontent.com/233360/102891309-4464bf80-445e-11eb-8a46-8813feb79990.png)

**Comment by jlfwong** [comment]
Thanks for the donation @titpetric!

When I have time to work on speedscope, this will be my next priority! I'll keep this thread updated with any progress.

**Comment by jlfwong** [comment]
This is proving more difficult than I originally thought for two reasons:

1. Installing valgrind on macOS is shockingly difficult now, so I haven't been able to easily generate new files. I've similarly struggled to get other things that spit out callgrind profiles up and running on my mac, so any test files you can provide would be helpful in evaluating this, @titpetric 

2. Callgrind profiles don't uniquely define a flamegraph, so they therefore ambiguously define a flamegraph. I'll post an example of how this is the case when I push the WIP code I have for importing callgrind profiles up. What this means in practice is that the resulting flamegraphs may be misleading on occasion. I don't see a good way of avoiding this, since it's fundamental to converting call graphs to flamegraphs.

**Comment by jlfwong** [comment]
Okay, the initial code for this is up, though it's difficult for me to develop confidence this is right without more sample files from people where I can compare the output shown in Qcachegrind with what's shown in speedscope.

[This comment](https://github.com/jlfwong/speedscope/pull/331/files#diff-a71f6ecedb658307b07ee12f88d0e60dfc9dca4c739ff4666bb31853541fdaf0R1-R86) from the WIP code shows an example that demonstrates the fundamental ambiguity inherent in importing callgrind profiles into speedscope.

Definitely interested in feedback from anyone interested in using the output of this format, including @titpetric

**Comment by titpetric** [comment]
I've asked a coworker to source some xhprof and xdebug trace files, might take a few ______ (unit of time) :)

**Comment by zobo** [comment]
Here are some Cachegrind files I made with Xdebug 3 and a clean wordpress install. Let me know if you need something else!

[cachegrind.zip](https://github.com/jlfwong/speedscope/files/5925821/cachegrind.zip)

**Comment by jlfwong** [comment]
@zobo Sweet, thank you!

**Comment by jlfwong** [comment]
Okay! The first cut of this is published as part of [speedscope@1.13.0](https://www.npmjs.com/package/speedscope/v/1.13.0), and is live on https://www.speedscope.app/.

@zobo Thanks again for the files. I used those to test, and caught some real issue I wouldn't have otherwise! If you get a chance, please give it a spin and see if it's helpful.

**Comment by zobo** [comment]
Great @jlfwong! Will do.
I'll drop you the xhprof files in another issue when I get the chance. Thanks a lot again!

**Comment by joaospinto** [comment]
I think there are some issues with the `callgrind` format integration. I'm trying to visualize some profiles that I recorded via https://github.com/fabianp/yep, which outputs `.prof` files, which I'm then converting to the `callgrind` output format with the `google-pprof` tool. I suspect something isn't right in the handling of cycles.

This is what I'm seeing with `speedscope`:

<img width="1725" alt="Image" src="https://github.com/user-attachments/assets/99bcbe5e-8593-4068-a8ac-19fa48a42023" />

There are certainly many more things in this profile, though:

<img width="1495" alt="Image" src="https://github.com/user-attachments/assets/622118c0-3298-4574-9d01-151aa1b3d2d1" />

Unfortunately, the full profile contains some information that I can't share on GitHub, but hopefully the images above are sufficiently for creating a minimal example to reproduce this issue.
