### ISSUE TITLE
Fails during importing of perf.data file

### ISSUE THREAD

**Issue by gogainda** [jlfwong/speedscope#180]
Cannot import this file on https://www.speedscope.app/

[perf-8922.zip](https://github.com/jlfwong/speedscope/files/2475762/perf-8922.zip)

**Comment by jlfwong** [comment]
Hi @gogainda!

What did you use to record that profile? This looks like a binary file format that speedscope just doesn't support at all.

**Comment by gogainda** [comment]
I was using https://github.com/jvm-profiling-tools/perf-map-agent and ```perf-java-flames <pid> <perf-record-options>``` in particular. Looks like I need text based format to make it work

**Comment by gogainda** [comment]
closing it
