### ISSUE TITLE
Format support: Haskell GHC JSON Profile

### ISSUE THREAD

**Issue by trishume** [jlfwong/speedscope#182]
See [the Haskell profiling documentation](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html) for a description of the `-pj` JSON format. It won't support the time sort view since the profile only includes a summary and not the individual samples.

I currently plan on implementing this myself and submitting a PR.

**Comment by jlfwong** [comment]
Hi @trishume!

That sounds good to me! I'm happy to review and merge a PR for that. Let me know if there are steps along the way that aren't super clear for where to write this code.

P.S. You should stop by Figma again ;)
