### ISSUE TITLE
Do not ellipsize file name

### ISSUE THREAD

**Issue by Yajo** [jlfwong/speedscope#191]
When hovering over calls, the file & method is ellipsized to the left, which is useless in my case (and I imagine also for others):
![captura de pantalla de 2018-11-15 11-05-05](https://user-images.githubusercontent.com/973709/48549061-a4272e80-e8c6-11e8-8406-4b62e9d91269.png)

It shouldn't be ellipsized, or at least it should be to the right, because I think it's more interesting the file name and function name than the system path where it is found.

**Comment by jlfwong** [comment]
Hi @Yajo!

I've heard this feedback from a few people now, and I think at least one version of it should be pretty easy to fix.

The relevant code to fix this is here: https://github.com/jlfwong/speedscope/blob/ad49dacb29f6b9dab22171af9da92e9b44abf909/src/views/hovertip.tsx#L11.

I'd accept a PR to make the tooltip extend to the edge of the container with a margin

**Comment by miso11** [comment]
Hi, is enough to only increase TOOLTIP_WIDTH_MAX to 900?

**Comment by jlfwong** [comment]
@miso11 Sure, I'd accept a PR to do that, assuming it never overflows the window (which I don't think it should)

**Comment by jlfwong** [comment]
I'll close this for now, though I'd also be happy to take a more complete PR that does ellipsization in the middle of the string rather than the end
