### ISSUE TITLE
Format support: Import from vmprof

### ISSUE THREAD

**Issue by belm0** [jlfwong/speedscope#213]
vmprof is a good sampling profiler for Python (native function support, etc.), but it has a terrible UI (https://github.com/vmprof/vmprof-server/issues/2, https://github.com/vmprof/vmprof-server/issues/38).

I'm wondering if would take much to convert vmprof to speedscope format.

  https://vmprof.readthedocs.io/en/latest/format.html

I'm aware of effort for pyspy to output one of the speedscope formats, but that seems like a work in progress (as is pyspy's native function support).

**Comment by belm0** [comment]
indeed the vmprof data appears to just be a list of samples:

`<lang>:<symbol name>:<line>:<file>`
```
py:<module>:15:/.../lib/python3.7/string.py
py:Formatter:175:/.../lib/python3.7/string.py
py:Template:78:/.../lib/python3.7/string.py
py:_TemplateMetaclass:55:/.../lib/python3.7/string.py
py:<module>:24:/.../lib/python3.7/logging/__init__.py
py:NullHandler:2059:/.../lib/python3.7/logging/__init__.py
py:LoggerAdapter:1684:/.../lib/python3.7/logging/__init__.py
```

**Comment by belm0** [comment]
I see, I can use https://github.com/methane/vmprof-flamegraph for conversion from vmprof to brendan gregg's flamegraph format, which speedscope supports natively.

**Comment by jlfwong** [comment]
@belm0 If the conversion from vmprof to brendan gregg's flamegraph format is lossy, I'd accept a PR to add support specifically for vmprof
