### ISSUE TITLE
Add 'cycles' as a ValueUnit option in JSON schema 

### ISSUE THREAD

**Issue by elalfer** [jlfwong/speedscope#224]

**Comment by jlfwong** [comment]
Hi @elalfer! Can you provide a bit more context around what you're hoping to get out of this? The value of having units is that they can be aggregated appropriately for display. For example, if you have a unit of `microseconds`, an you have a value of `1230000`, then we can display that as `1.23s`. What would you hope to get out of a `cycles` unit?

The schema already supports `none` as a unit, which I suspect will do almost the same thing as cycles?

**Comment by jlfwong** [comment]
I'm going to close this out for inactivity since I'm not sure what the request is here
