### ISSUE TITLE
Add flamescope and pyspeedscope to documentation

### ISSUE THREAD

**Issue by windelbouwman** [jlfwong/speedscope#225]
Hi,

Just wanted to inform about two extra language supports:

- rust: https://github.com/coolreader18/flamescope
- python: https://github.com/windelbouwman/pyspeedscope

Thanks for creating speedscope! It works nicely!

**Comment by jlfwong** [comment]
Ah! Thanks for letting me know! When have some time I'll update the documentation with this information!

**Comment by jlfwong** [comment]
Oh whoops, I did this a while ago but never closed this issue: https://github.com/jlfwong/speedscope/commit/68683aa054e803c079b4475a111fa579d32d2b3f#diff-04c6e90faac2675aa89e2176d2eec7d8
