### ISSUE TITLE
README should compare to chrome://tracing

### ISSUE THREAD

**Issue by pwinston** [jlfwong/speedscope#227]
I gather chrome tracing is somewhat a "competitor" of speedscope, but it would be nice if the README explained the relationship between the two projects. What problems or limitations with chrome tracing did speedscope set out to solve?

I'm guessing speedscope has less features, but the UI is simpler/nicer? Does speedscope perform better? Or does it maybe perform worse, but good enough for most uses? It's very hard to know this information, but it seems like the developers know this cold, so why not share it?

Also it would be nice to see summary of what file formats take advantage of what speedscope features. For example, what do I give up or gain by using each format? Does using the chrome tracing format give me 100% of the speepscope features? Or what is gained by using speedscope's own format?

I can understand some people would rather not mention "competing" projects. But I feel like without stating the pros and cons, or even just the goals, people aren't confident in choose the lesser known option. For me I thought speedscope looked really cool, but without knowing really what the advantages were I just opted to use chrome tracing, for now.

**Comment by jlfwong** [comment]
Hi @pwinston!

Thanks for the carefully considered comment!

speedscope was not created as a competitor of chrome://tracing. It happened to kind of end up that way, but that's not the goal.

The design goal of speedscope was to be a profile viewer that would support import of a variety of different profiling formats and run at close to 60fps even for massive (> 100MB profiles). Chrome tracing imports only its own format, and leaves it up to you as a developer to find some way of converting your profile into Chrome tracing's own profile format.

I'm not really interested in building up a feature matrix for speedscope vs other common profile viewers (there are many, not just chrome tracing). IMO the best way of evaluating is just by trying it. The investment cost to trying it is really low, and it'll give you a better sense of which is useful in what scenario than a textual summary will.

For your own purposes, I'm happy to talk about the differences I'm aware of, but I'd rather not put this in the README.

On the specific note of chrome tracing, I find its interfacing really frustrating to work with, and it supports only a time-ordered view whereas speedscope supports left-heavy and bottoms-up views that are described in the README. An important thing that chrome tracing offers that speedscope doesn't is the ability to see several profiles (for e.g. several different threads) on the same time axes so you can correlate events on one thread with another. Adding that to speedscope is tracked in #117, but I'm not doing active development on this project right now, so it's unlikely to be resolved for some time.

If you're happy with chrome://tracing and don't find yourself frustrated by it, please keep using it!

**Comment by pwinston** [comment]
Thanks for the detailed response. I think in Brendan Gregg's terminology Speedscope does "flame graphs" and chrome tracing does "flame charts"? If so that's a huge difference right there than I wasn't appreciating. I think the difference between the two types of visualizations is lost on a lot of people, I think flame charts are not obvious because people assume the x-axis has to be time. I feel like "positioning" speedscope as to what it does or doesn't do would be helpful for everyone. Not everyone has the bandwidth to trial all options. Certainly though your call! We are using chrome's format, so I guess we can try it in both tools. Thanks!

**Comment by jlfwong** [comment]
> I think in Brendan Gregg's terminology Speedscope does "flame graphs" and chrome tracing does "flame charts"?

chrome tracing does flame charts, speedscope supports both
