### ISSUE TITLE
Format support: Import from py-spy

### ISSUE THREAD

**Issue by benfred** [jlfwong/speedscope#232]
Thanks for this project!

py-spy v0.2 has the ability to write out speedscope formatted profiles (using the code you contributed to rbspy): ```py-spy record -o profile.json -f speedscope -- python myprogram.py``` - it would be cool if we could add a note of this to the speedscope documentation =).

**Comment by jlfwong** [comment]
Yesss that's awesome! Thanks for doing that!

If you'd like this to happen ASAP, if you can write some markdown in the same format as https://github.com/jlfwong/speedscope/wiki/Importing-from-rbspy-(ruby), then I'm happy to mostly copy-and-paste it into the wiki and update the README.

I'm also happy to write that documentation myself, but then I'll need to take the time to verify that it's actually working, which will take me a little longer.

**Comment by benfred** [comment]
Thanks! Here is some markdown modified from the rbspy wiki:

---

[py-spy](https://github.com/benfred/py-spy) is a profiler that lets you profile Python processes that are already running.

py-spy has an explicit output format for speedscope (See https://github.com/benfred/py-spy/issues/115).

To record a profile on an already-running process with rbspy, run:

```
sudo py-spy record --pid $PID --format speedscope -o profile.speedscope.json
```
Then drop the resulting profile.speedscope.json into https://www.speedscope.app/

To view it offline, you'll need to install speedscope via npm:

```
npm install -g speedscope
```

Then you should be able to open it like so:

```
speedscope /path/to/profile.speedscope.json
```

**Comment by jlfwong** [comment]
That's great, thanks! I updated the README and aded a page to the wiki. Thanks for adding support & for providing the documentation!

**Comment by hammer** [comment]
@jlfwong there's a small typo in the wiki: "To record a profile on an already-running process with `rbspy`" should be changed to `py-spy`.

**Comment by jlfwong** [comment]
@hammer Fixed, thanks!
