### ISSUE TITLE
.NET Core 3 supports speedscope - wiki update

### ISSUE THREAD

**Issue by 0x6a62** [jlfwong/speedscope#237]
.NET Core (starting at v3) supports saving traces in speedscope format.  I made a wiki update to show how to do it.  Since doing github PRs for wikis are kind of broken, I created a personal repo with the change.  Below is the file you can add to the wiki to get the new documentation.  Let me know if you have any questions, etc.

https://github.com/0x6a62/speedscope/blob/master/Importing-from-dotnetcore.md

**Comment by jlfwong** [comment]
Thanks!

One question -- there's a line that says "1) Directly, define the format what collecting the trace results." I'm not sure what this is intended to say.

Did you mean to say something like "1) Specify the trace format at trace creation time"?

**Comment by 0x6a62** [comment]
Correct, "1) Specify the trace format at trace creation time." is the intent.  I apparently fail at proofreading when I'm sleep-deprived.

**Comment by jlfwong** [comment]
Added to the wiki and updated the README, thanks!
