### ISSUE TITLE
UX Sandwitch: find particular symbol name

### ISSUE THREAD

**Issue by guettli** [jlfwong/speedscope#243]
I want to find a particular symbol name in the long list of the sandwitch view.

Unfortunately ctrl-f (Chrome) does not work.

How to find a particular symbol name?

ctrl-f only works for the names which are visible on the current page.

I monitored a test-run which took 30 minutes. There are a lot of symbol names....

**Comment by jlfwong** [comment]
Hi @guettli! This is indeed a current limitation. I believe this is captured by https://github.com/jlfwong/speedscope/issues/38. Closing this one as a duplicate
