### ISSUE TITLE
Unrecognized format on Haskell

### ISSUE THREAD

**Issue by tuomohopia** [jlfwong/speedscope#259]
I keep hitting `Unrecognized format` error popup when trying to see profile file generated by Haskell (Stack).

Here's how I run the profiling:
```sh
stack test --profile --test-arguments "+RTS -pj -RTS"
```

Am I doing something wrong here?

I'm on
* WIN10
* Stack ver2.1.3
* `lts-14.3` (GHC 8.6.5)

**Comment by jlfwong** [comment]
Hi @tuomohopia!

I've probably written 10 lines of Haskell in my life, so I have no idea. If you provide a profile, that would be more helpful to me than the command sequence (though the command sequence I'm sure is very helpful for someone familiar with Haskell!)

CC @trishume who wrote the Haskell format importer for speedscope.

**Comment by tuomohopia** [comment]
Thanks for taking a look at the problem

The profiling file is here:
https://drive.google.com/file/d/1xjGOe4zhTKRkO2D5RrROTGkNIM6UDDgz/view?usp=sharing

This may be a problem related to Haskell's `stack` (build tool). It's just quite hard to understand what the problem is, or rather why the `speedscope` parser fails to recognize this file.

**Comment by trishume** [comment]
Unfortunately it was long enough ago that I completely forget everything to do with the Haskell importer I wrote and how Haskell profiling works in general. You could try cloning speedscope and inserting print statements or something to debug the haskell importer yourself, I don't think it was very much code.

**Comment by tuomohopia** [comment]
Thanks, I'll see what I can do about it. I got the feeling the `stack` build tool is somehow producing a faulty file, but it would be insightful to make `speedscope` spell me out what it thinks is the actual problem.

**Comment by tuomohopia** [comment]
For the record, this is probably a Haskell Stack Windows compatibility issue. I ran a test profiling on MacOS and it visualized it beautifully. So I doubt there's any bug with `speedscope` regarding this.

I'll close this now.
