### ISSUE TITLE
Document ruby-prof support in the wiki?

### ISSUE THREAD

**Issue by palasha** [jlfwong/speedscope#265]
I've been working on performance profiling at work recently, and we use `ruby-prof`, which wasn't supported with speedscope, untill now!

I put together https://github.com/chanzuckerberg/ruby-prof-speedscope that's available as a Ruby gem under `ruby-prof-speedscope`. It provides an output printer module for RubyProf results that's compatible with speedscope's event based trace format.

Would it be valuable to document this in the wiki here? I wasn't sure how to open a pull request specifically for that.

**Comment by jlfwong** [comment]
Hi! The easiest thing for me is if you just write up the documentation you'd like to see in markdown, then I can copy and paste it myself.

If you could format it similarly to https://github.com/jlfwong/speedscope/wiki/Importing-from-rbspy-(ruby), that would be helpful!

**Comment by palasha** [comment]
Sounds great, i'll do that today.

**Comment by palasha** [comment]
[`ruby-prof`](https://ruby-prof.github.io/) is a tracing ruby profiler that lets you profile specific parts of the code that you choose.

The gem `ruby-prof-speedscope` (https://github.com/chanzuckerberg/ruby-prof-speedscope) provides a "Printer" that outputs ruby-prof profiles in the speedscope format.

To record and save a profile with `ruby-prof`, do something like the following:
```ruby
# Collect the profile
results = RubyProf.profile do
  # ... some slow stuff
end

# Save the results
File.open("/tmp/profile.speedscope.json") do |f|
  RubyProf::SpeedscopePrinter.new(results).print(f)
end

```
Then drop the resulting `profile.speedscope.json` into https://www.speedscope.app/
To view it offline, you'll need to install speedscope via `npm`:
```
npm install -g speedscope
```
Then you should be able to open it like so:

```
speedscope /tmp/profile.speedscope.json
```

**Comment by jlfwong** [comment]
Updated the README and the wiki! Thanks!
