### ISSUE TITLE
profileURL hash parameter not working (branch preact-upgrade)

### ISSUE THREAD

**Issue by BartmanAbyss** [jlfwong/speedscope#271]
Using the profileURL hash parameter to immediately load a profile doesn't work.
I think I tracked it down to `this.props.setGLCanvas` beging called here https://github.com/jlfwong/speedscope/blob/c0d65f873a9bf30aac105f19ead64713eeabe9e7/src/views/application.tsx#L68 before `store.subscribe` is called here
https://github.com/jlfwong/speedscope/blob/c0d65f873a9bf30aac105f19ead64713eeabe9e7/src/lib/preact-redux.tsx#L51 because `useEffect()` delays this call until the next frame. I was abe to fix the issue by replacing `useEffect` with `useMemo`.

**Comment by jlfwong** [comment]
Oh interesting -- thanks for the report!

Do you have an easy reproduction for this? I didn't author the `#profileURL` thing so I don't actually have a great setup for testing this at the moment.

I'm also curious why you ended up testing on the preact-upgrade branch -- are you building off of it? I'm very likely to change a lot of stuff in that branch before landing it.

I don't think `useMemo` will work here because we need to do teardown when the component gets unmounted unless I'm misunderstanding something here.

**Comment by BartmanAbyss** [comment]
I‘m trying to integrate speedscope into a project that uses preact 10, so the master branch wouldn‘t quite work for me.
For a repro, just `npm run serve` and use any profileURL. You‘ll see that the loading never finishes. With my fix, you‘ll get your profile or an error message that the profile has not been found or is an invalid file format. 
I had a look at the preact/hooks source code, and it seems that `useMemo` and `useEffect` are essentially the same, albeit `useEffect` is delaying its execution until the next `requestFrame`.

**Comment by jlfwong** [comment]
From the docs:

> Remember that the function passed to useMemo runs during rendering. Don’t do anything there that you wouldn’t normally do while rendering. For example, side effects belong in useEffect, not useMemo.

My guess is `useLayoutEffect` is probably a better candidate -- can you see if that works? https://reactjs.org/docs/hooks-reference.html#uselayouteffect

**Comment by BartmanAbyss** [comment]
Yes, that seems to work. Good catch.

**Comment by jlfwong** [comment]
FWIW, I wouldn't recommend building on top of the preact-upgrade branch for a while unless you're okay with running stale code (which is honestly probably fine if speedscope already does what you want). The code for that is likely to change fairly significantly before I land it.

**Comment by jlfwong** [comment]
FYI I found another subtle bug with my implementation of `useSelector` that was fixed here: https://github.com/jlfwong/speedscope/pull/279/files
