### ISSUE TITLE
Broken stack traces

### ISSUE THREAD

**Issue by swift-kim** [jlfwong/speedscope#272]
For example, I have this profile data generated from my application:

https://www.speedscope.app/#profileURL=https://swift-kim.github.io/warehouse/data/HeartRateMonitor.10068.speedscope.json

In the time-order view, I can see some weird stack frames like `xamarin.forms.platform.tizen!Xamarin.Forms.Forms.SetupInit` (frame 7) which shouldn't appear for more than 103.8ms (1146.5 - 1250.3) according to the raw data.

I also made a simple python program which prints a callstack at a specific time from a speedscope file.

https://gist.github.com/swift-kim/f6f2e2450fe91708f97656aaf6a35281

When I run this program with `HeartRateMonitor.10068.speedscope.json 280` as arguments, the result looks like:

```
UNMANAGED_CODE_TIME
heartratemonitor!HeartRateMonitor.Views.MeasurementPage.InitializeComponent()
heartratemonitor!HeartRateMonitor.Views.MeasurementPage..ctor()
heartratemonitor!HeartRateMonitor.App..ctor()
heartratemonitor!HeartRateMonitor.Program.OnCreate()
Tizen.Applications.UI!Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(int)
Tizen.Applications.UI!Tizen.Applications.CoreBackend.UICoreBackend.Run(class System.String[])
Tizen.Applications.Common!Tizen.Applications.CoreApplication.Run(class System.String[])
Tizen.Applications.UI!Tizen.Applications.CoreUIApplication.Run(class System.String[])
heartratemonitor!HeartRateMonitor.Program.Main(class System.String[])
Thread (10068)
Threads
(Non-Activities)
Process32 Process(10068) (10068) Args:
```

However, speedscope.app shows a different result with some missing stack frames (`heartratemonitor!HeartRateMonitor.*`). (This is only an example.)

```
UNMANAGED_CODE_TIME
> UNMANAGED_CODE_TIME
> xamarin.forms.core!Xamarin.Forms.Application..ctor()
> xamarin.forms.platform.tizen!Xamarin.Forms.Platform.Tizen.FormsApplication.InitializeWindow()
> Tizen.Applications.UI!Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(int)
> Tizen.Applications.UI!Tizen.Applications.CoreBackend.UICoreBackend.Run(class System.String[])
> Tizen.Applications.Common!Tizen.Applications.CoreApplication.Run(class System.String[])
> UNMANAGED_CODE_TIME
> xamarin.forms.platform.tizen!Xamarin.Forms.Forms.SetupInit(class Tizen.Applications.CoreApplication,value class System.Nullable`1<value class Xamarin.Forms.InitializationOptions>)
> heartratemonitor!HeartRateMonitor.Program.Main(class System.String[])
> Thread (10068)
> Threads
> (Non-Activities)
> Process32 Process(10068) (10068) Args:
```

At the same time, PerfView works nicely although it doesn't have a time-order view.

![image](https://user-images.githubusercontent.com/40190588/82650313-78bc9700-9c55-11ea-8262-42f46d9d9752.png)

Since I'm not good at TypeScript, could anybody help me with finding the underlying issue?

#### Appendix
- Application source code (Tizen application): https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/HeartRateMonitor
- Raw nettrace file: https://github.com/swift-kim/warehouse/raw/master/data/HeartRateMonitor.10068.nettrace.zip

**Comment by jlfwong** [comment]
Thanks for the clear report!

The bug here is that the provided input profile doesn't match up it's `O` and `C` events symmetrically. Here's the start of the profile:

```
[
  { "type": "O", "frame": 0, "at": 1130.948461 },
  { "type": "O", "frame": 1, "at": 1130.948461 },
  { "type": "O", "frame": 2, "at": 1130.948461 },
  { "type": "O", "frame": 3, "at": 1130.948461 },
  { "type": "O", "frame": 4, "at": 1130.948461 },
  { "type": "O", "frame": 5, "at": 1130.948461 },
  { "type": "C", "frame": 5, "at": 1136.3827679539413 },
  { "type": "O", "frame": 6, "at": 1136.382768 },
  { "type": "O", "frame": 5, "at": 1136.382768 },
  { "type": "O", "frame": 5, "at": 1138.993153 },
  { "type": "C", "frame": 5, "at": 1138.9931530194092 },
  { "type": "C", "frame": 6, "at": 1138.9931530194092 }
]
```

The specific problem is the last 5 events. There's a sequence here that looks like:

```
O 6
O 5
O 5
C 5
C 6
```

The python script you made validates that the closed frame is *in* the stack when it's closed, but it doesn't validate that it's at the *top* of the stack when it's closed. Speedscope doesn't support closing stack frames that aren't at the top because it doesn't make any sense. They have the same timestamp here so you could argue that they close at the "same time", but I'd rather make file format outputters be responsible for well formed inputs than make speedscope do lookahead to figure out if it needs to look at many events and sort them.

All that said, I agree this is bad behavior in speedscope: it should fail input in this scenario rather than display the wrong thing. I'll put a PR to make this fail loudly.

**Comment by jlfwong** [comment]
Oh, I see -- this is probably a bug with the code written in https://github.com/microsoft/perfview/blob/master/src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs. I'll file a bug.

**Comment by swift-kim** [comment]
Thanks and I'll also take a look if it was a bug in TraceEvent!
