### ISSUE TITLE
Expose embeddable trace component

### ISSUE THREAD

**Issue by JustinBeckwith** [jlfwong/speedscope#278]
👋 I've popped in here a few times previously with PRs, but wanted to open a real feature request for my purposes.  I'd love to use this as a stand alone component, embedded in my own application.   For example, d3 flame charts allow you to effectively hand it a `div`, and some JSON, and it will render the chart inline.

Is this something that's readily possible today?  Or any tips towards where I'd start poking for a PR?

Thanks!

**Comment by jlfwong** [comment]
Hi! I'm a little confused because this is exactly what's discussed in #16 which you also commented in. Are you asking for something different here?

**Comment by JustinBeckwith** [comment]
Ah, there it is!  Apologies - I was picking this back up, and went searching for issues *I* opened, and completely forgot about that one.  Ignore me 😆
