### ISSUE TITLE
Error whlie loading dotnet-trace output

### ISSUE THREAD

**Issue by doctornick42** [jlfwong/speedscope#286]
Hi! I'm trying to use dotnet-trace tool with Speedscope format to visualize the result in Speedscope. I' running dotnet-trace like this:
```
dotnet-trace collect --process-id 1 --format Speedscope --duration 00:00:01:00
```

When I upload it to speedscope.app I see this error:
> Failed to load format Error: Tried to leave frame "UNMANAGED_CODE_TIME" while frame "CPU_TIME" was at the top at 4.879935016929625

If I run dotnet-trace with `Nettrace` format I can open the resulting file with PerfView without any problems.
I don't have any experience with Speedscope so I may do something wrong, so please help me to realize how could I solve the issue.

I'm uploading my trace file to show what exactly I'm trying to display.
[trace.speedscope.zip](https://github.com/jlfwong/speedscope/files/4787496/trace.speedscope.zip)

Thanks in advance!

**Comment by jlfwong** [comment]
Hi @doctornick42!

I'm pretty sure this is a bug in dotnet-trace. 

See: 
- https://github.com/jlfwong/speedscope/issues/272
- https://github.com/microsoft/perfview/issues/1178
- https://github.com/jlfwong/speedscope/issues/285
