### ISSUE TITLE
Can't open result of dotnet trace collect --process-id 35043 --format Speedscope in Chrome on MacOS

### ISSUE THREAD

**Issue by darraghjones** [jlfwong/speedscope#289]
Getting this error:

`Failed to load format Error: Tried to leave frame "System.Private.CoreLib!System.Threading.ExecutionContext.RunInternal(class System.Threading.ExecutionContext,class System.Threading.ContextCallback,class System.Object)" while frame "UNMANAGED_CODE_TIME" was at the top at 1.3720699548721313`

**Comment by jlfwong** [comment]
Hi @darraghjones!

I'm pretty sure this is a bug in perfview.

See: 
- https://github.com/jlfwong/speedscope/issues/272
- https://github.com/microsoft/perfview/issues/1178
- https://github.com/jlfwong/speedscope/issues/285

This is also both of the most recent issues filed & closed: https://github.com/jlfwong/speedscope/issues?q=is%3Aissue+is%3Aclosed
