### ISSUE TITLE
Failed to load format Error: Tried to leave frame...

### ISSUE THREAD

**Issue by AlexeyKhrenov** [jlfwong/speedscope#290]
When trying to import speedscope.json file into the app it shows: 
_"Something went wrong. Check the JS console for more details"._ 
Checking the JS console for details, it shows:

Failed to load format Error: Tried to leave frame "System.IO.Compression!System.IO.Compression.Inflater.Inflate(value class FlushCode)" while frame "Dublin!Dublin.ReaderWriterWorkers.ConcurrentQueue`1[System.__Canon].TryDequeue(!0&)" was at the top at 6.731634050231934
    at n._leaveFrame (speedscope.ca4dd7be.js:156)
    at n.leaveFrame (speedscope.ca4dd7be.js:156)
    at speedscope.ca4dd7be.js:162
    at a (speedscope.ca4dd7be.js:162)
    at speedscope.ca4dd7be.js:162
    at Array.map (<anonymous>)
    at s (speedscope.ca4dd7be.js:162)
    at import.67a00871.js:111
    at Generator.next (<anonymous>)
    at s (import.67a00871.js:111)

Here's the original file:
https://drive.google.com/file/d/1uk07C4YjV5XrGUEWM5ZehARAgUO8tuxO/view?usp=sharing

Probably this issue could be caused by improper file format. It was created with dotnet trace.

**Comment by bjorn3** [comment]
Quoting @jlfwong at https://github.com/jlfwong/speedscope/issues/289#issuecomment-647829198:

> I'm pretty sure this is a bug in perfview.
>
> See:
>
> * #272
> * microsoft/perfview#1178
> * #285
>
> This is also both of the most recent issues filed & closed: https://github.com/jlfwong/speedscope/issues?q=is%3Aissue+is%3Aclosed

**Comment by AlexeyKhrenov** [comment]
Ok, thank you!
