### ISSUE TITLE
Failed to open profile file

### ISSUE THREAD

**Issue by PraveenRamakrishna** [jlfwong/speedscope#291]
Failed to open in profile.v8log.json file in [https://www.speedscope.app/], also get same error when I open generated .html file. attaching error from console and profile.v8log.json  file I am using. 

`Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at showNeg.js:241
    at XMLHttpRequest.onDefaultReadyStateChangeHandler (showNeg.js:311)
import.67a00871.js:111 Importing as --prof-process v8 log
speedscope.ca4dd7be.js:172 Failed to load format SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at import.67a00871.js:111
    at Generator.next (<anonymous>)
    at s (import.67a00871.js:111)`

Could you please help.

[profile.v8log.zip](https://github.com/jlfwong/speedscope/files/4865000/profile.v8log.zip)

**Comment by jlfwong** [comment]
Hi @PraveenRamakrishna! Thanks for the report -- I think this is the first report I've had of someone trying to import UTF-16 encoded text into speedscope, which previously didn't work at all. I have a patch in #314 which I'll try to get out sometime this week.

Sorry for the very delayed response! Out of curiosity, do you remember how you ended up with a file encoded like this?

**Comment by jlfwong** [comment]
This should now be fixed on https://www.speedscope.app/
