### ISSUE TITLE
speedscope is not defined

### ISSUE THREAD

**Issue by qiaochunmei** [jlfwong/speedscope#292]
Do you encounter this problem when you use it alone

**Comment by jlfwong** [comment]
Hi @qiaochunmei,

I'm afraid I can't help without steps to hit this error.

If you can provide steps to reproduce the problem, I'm happy to re-open the issue and take a look.

**Comment by qiaochunmei** [comment]
const jsSource = `speedscope.loadFileFromBase64(${JSON.stringify(filename)}, ${JSON.stringify(
      sourceBase64,
    )})`
console.log(speedscope, 55555);
源码里这个打印是没有定义

**Comment by qiaochunmei** [comment]
源码里这个上面有挂载方法，应该是有值的？speedscope.loadFileFromBase64
