### ISSUE TITLE
Unable to display trace file from dotnet trace

### ISSUE THREAD

**Issue by mrj001** [jlfwong/speedscope#299]
I generated a trace file like this:
```
$ dotnet trace collect -p 19552 --profile cpu-sampling
$ dotnet trace convert trace.nettrace --format SpeedScope
```
When I try to open it in speedscope app (in either Firefox or Safari), I get:

> Something went wrong.
> Check the JS console for more details.

The JS Console contains this error:

> [Log] Failed to load format – Error: Tried to leave frame "DigitPower!DigitPower.Program.DigitSum(int64)" while frame "CPU_TIME" was at the top at 33.42511303677384 (speedscope.c9e86af9.js, line 174)
> Error: Tried to leave frame "DigitPower!DigitPower.Program.DigitSum(int64)" while frame "CPU_TIME" was at the top at 33.42511303677384

This is the file causing the trouble:
[trace.speedscope.json.gz](https://github.com/jlfwong/speedscope/files/4979624/trace.speedscope.json.gz)

I've been unable to display any profiles recently, so this is not unique to this project.

**Comment by jlfwong** [comment]
Hi @mrj001! This is most likely a now-resolved bug in `dotnet trace`.

See:
- https://github.com/jlfwong/speedscope/issues/272
- https://github.com/jlfwong/speedscope/issues/286
- https://github.com/jlfwong/speedscope/issues/289
