### ISSUE TITLE
Ignore&squash noisy functions

### ISSUE THREAD

**Issue by radex** [jlfwong/speedscope#301]
Hi, I'm dealing with an application that sometimes has really deep stack traces, most of which are framework functions that most of the time don't contribute any valuable information, but they do make it more difficult to read the profile, since I have to scroll up and down to see the leaves.

Example:

<img width="1286" alt="Captura de pantalla 2020-07-28 a las 11 14 24" src="https://user-images.githubusercontent.com/183747/88645073-fe304d80-d0c3-11ea-9921-91347629ba56.png">

The list of these noisy functions is fairly short for me, and I could pretty easily list them. So it would be useful for me if I could drop in a text file with a list of functions to ignore in the profile (they could be squashed into a single stack element `(ignored)`).

The way I see it is, the ignored functions would be prepared by hand by the user (so almost no UI needed) as a text file. When drag&dropped, some indicator could show up that there are ignored functions, and a shortcut `i` could toggle between squashing and not squashing ignored functions (analogous to `r`). And the processing would probably be easiest to implement analogous to `getProfileWithRecursionFlattened`

I'm willing to put in the work to implement this, of course, though basic guidance would be appreciated -- but would this feature be accepted?

**Comment by radex** [comment]
for detailed design, I think the way I'd squash those stacks is from:

```
a;b
a;b;i1
a;b;i1;i2;i3
a;b;i1;i2;i3;c
a;b;i1;i2;i3;c;i4;d
a;b;i1;i2;c
a;b;i1;i2
```

(where i1,i2,i3 are ignored functions) to:

```
a;b
a;b;i1
a;b;(ignored);i3
a;b;(ignored);c
a;b;(ignored);c;(ignored);d
a;b;(ignored);c
a;b;(ignored);i2
```

so ignored functions would still appear but only when they're leaves

**Comment by jlfwong** [comment]
Hi @radex, sorry for the slow response here.

I think if I wanted to support stack filtering somehow, dropping a file like this is unlikely to be the interface I'd want to expose.

If you'd like some guidance on how to implement this just for you to play around with it in your own fork, I'm happy to do that.

**Comment by radex** [comment]
> I think if I wanted to support stack filtering somehow, dropping a file like this is unlikely to be the interface I'd want to expose.

_Would you_ want to support stack filtering, if I put in the time to make the interface better than dropping a file?
