### ISSUE TITLE
What's the correct way of hosting a local speedscope via nginx

### ISSUE THREAD

**Issue by amosbird** [jlfwong/speedscope#309]
Hi, I've downloaded speedscope from https://github.com/jlfwong/speedscope/releases and tried setting up an nginx section like this 

```
        server {

            listen 29998;
            server_name localhost;
            root /path/to/speedscope-1.9.0/assets;
            index /index.html;
        }
```

However, I ended up with an empty page when opening localhost:29998. What did I miss?

**Comment by bjorn3** [comment]
The last version with a self-contained archive on the release page is v1.7.0. For later versions you will need to compile them yourself using `npm install && npm prepack`. You will then find all files in `dist/release` if I read the build script correctly.

**Comment by amosbird** [comment]
Thanks!

**Comment by jlfwong** [comment]
Weird. I uploaded a release for v1.9.0, but GitHub said it was invalid and needed to be re-uploaded. https://github.com/jlfwong/speedscope/releases/tag/v1.9.0 should now have a working .zip file on it
