### ISSUE TITLE
Question: what are the time units?

### ISSUE THREAD

**Issue by jurc192** [jlfwong/speedscope#311]
I profiled a python program with `py-spy` and am visualizing the results on www.speedscope.app.
What are the units of time, displayed at the timeline? (time order view)
What about the bottom right box w/ "This instance" and "All instances"? What is the meaning of those numbers?
Thanks for help :)

**Comment by bjorn3** [comment]
`py-spy` uses samples as unit: https://github.com/benfred/py-spy/blob/0a409aa57f28fccfb0d94a8d2a16b2ed0d6c42d3/src/speedscope.rs#L143 `py-spy` is a sampling profiler, which means that it samples the current stack every so often. The default sample rate is 100Hz: https://github.com/benfred/py-spy/blob/fedd53bd799efdac33d5a41ad56b1bb8047684b4/src/config.rs#L83 It is possible for samples to be taken later than that though.

**Comment by jlfwong** [comment]
FWIW, speedscope's file format supports specifying the time unit: https://github.com/jlfwong/speedscope/blob/069c0194a6d3fd10f9cabce24735e3bd91fc1556/src/lib/file-format-spec.ts#L64-L65. So `py-spy` could specify this and make it easier to read in the resulting profiles

**Comment by benfred** [comment]
thanks for the suggestion @jlfwong  - I've created an issue in py-spy to track adding ValueUnit to py-spy profiles https://github.com/benfred/py-spy/issues/294
