### ISSUE TITLE
😿 Something went wrong. Check the JS console for more details.

### ISSUE THREAD

**Issue by mholec** [jlfwong/speedscope#329]
**File**
[speedscope file](https://drive.google.com/open?id=12YsgyD7rn4feL7PtyJoVDZDZbXZUNjPh)

**Chrome Console:**
speedscope.44364064.js:194 speedscope v1.12.1
DevTools failed to load SourceMap: Could not load content for https://www.speedscope.app/reset.8c46b7a1.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.speedscope.app/speedscope.44364064.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
speedscope.44364064.js:114 WebGL initialized. renderer: AMD Radeon Pro 555X OpenGL Engine, vendor: ATI Technologies Inc., version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
DevTools failed to load SourceMap: Could not load content for https://www.speedscope.app/import.cf0fa83f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.speedscope.app/source-map.438fa06b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.speedscope.app/demangle-cpp.1768f4cc.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://gccfnphpieojibjmnodiiobdapckkkfb/vendors/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
import.cf0fa83f.js:113 Importing as speedscope json file
speedscope.44364064.js:190 Failed to load format Error: Tried to leave frame "System.Private.CoreLib!System.Threading.ExecutionContext.RunInternal(class System.Threading.ExecutionContext,class System.Threading.ContextCallback,class System.Object)" while frame "System.Collections.Concurrent!System.Collections.Concurrent.ConcurrentDictionary`2[System.__Canon,Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher+ChangeTokenInfo].TryRemove(!0,!1&)" was at the top at 69.62325402281952
    at h._leaveFrame (speedscope.44364064.js:174)
    at h.leaveFrame (speedscope.44364064.js:174)
    at speedscope.44364064.js:180
    at a (speedscope.44364064.js:180)
    at speedscope.44364064.js:180
    at Array.map (<anonymous>)
    at s (speedscope.44364064.js:180)
    at import.cf0fa83f.js:113
    at Generator.next (<anonymous>)
    at s (import.cf0fa83f.js:113)

**Comment by jlfwong** [comment]
Hi @mholec !

This looks like it was probably a file generated by an old version of PerfView which had a buggy implementation of speedscope export. 

See https://github.com/microsoft/perfview/issues/1178. If you update perfview, the problem should go away.
