### ISSUE TITLE
Filter frames that don't contribute much

### ISSUE THREAD

**Issue by ocharles** [jlfwong/speedscope#330]
A profile I'm working with has a lot of helper functions that show up as frames, but actually contribute very little to the profile - they all have a self time of < 0.01%. It would be nice if I could just filter all frames with an aggregate self time of < *x*% out entirely, so I can focus on the meat of the problem.

**Comment by jlfwong** [comment]
Hi @ocharles!

Does the left heavy view help you out in this situation? That should sort things so that the bulk of the time is evident in the left.

You're definitely welcome to fork the repo and implement this, but I'm unlikely to do this myself or merge a PR for this.

**Comment by ocharles** [comment]
Hi Jamie, the left heavy view is great, but not quite what I'm looking for. But no problem, what I'll probably do is write something to filter my input before I give it to speedscope.app. Thanks for the quick reply!

**Comment by jlfwong** [comment]
> what I'll probably do is write something to filter my input before I give it to speedscope.app
For sure, that should definitely work!

If the format you're working with makes this a pain, you could also make something that processes speedscope's own file format, then export from speedscope -> run through your tool -> import back into speedscope. 

The schema of the file format is documented here: https://github.com/jlfwong/speedscope/blob/master/src/lib/file-format-spec.ts

**Comment by bvaughn** [comment]
Hi @ocharles. I was wondering if you would be willing to share your filtering code (assuming you ended up writing your own pre-filtering logic).

**Comment by ocharles** [comment]
Sorry, I don't have that anymore. I don't recall it being too hard to hack in though.
