### ISSUE TITLE
Display multiple scopes together on same page like chrome:tracing

### ISSUE THREAD

**Issue by alecazam** [jlfwong/speedscope#349]
I'm new to speedscope, but thought my other thread scopes were missing.  But the UI only displays one thread on-screen.   My game is split across multiple threads, and so seeing the overlap is important.  I found the popup to pick from the threads, but can the threads all be shown together on one screen?  Will read the docs and see if this is in there.

**Comment by alecazam** [comment]
I'd see this as checkboxes that hide the thread output in the "process/thread popup".  But by default all threads would be shown together.

**Comment by jlfwong** [comment]
Ah yeah, I'd really love to do this, but this is a lot of work, so I'm unlikely to get to this soon. #117 is the same issue, so I'm going to close this one out.
