### ISSUE TITLE
URL Hash parameter to set default view

### ISSUE THREAD

**Issue by danvk** [jlfwong/speedscope#355]
I'd like to link to speedscope.app (with some profile data loaded via `#profileURL=...`) and set the view to "Left Heavy", rather than the default "Time Order". Is there any way to do this? Would you accept a PR?

**Comment by djudd** [comment]
I'm also interested in this! Though in my case I'd want to set the default to Sandwich.

(My use case is an aggregated, synthetic profile consisting of samples taken from many requests, so time order is not meaningful.)

**Comment by jlfwong** [comment]
Hi @danvk! There's no way to do this at the moment. I'd accept a PR to do this, though as a fair warning I'm probably not going to be actively working on/deploying/publishing speedscope for a couple months

**Comment by djudd** [comment]
@jlfwong gentle nudge - no worries if you're not back to working on Speedscope yet, just making sure this didn't get lost.

**Comment by jlfwong** [comment]
Yep! Haven't put time back into this yet. Whenever I do a next push, this and other open pull requests will get some attention.
