### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TZanke** [jlfwong/speedscope#358]
I got a error after uploading my file:

![image](https://user-images.githubusercontent.com/1613368/113871036-c4672900-97b2-11eb-8465-babe68a355c6.png)

Just happens in Chrome Version 89.0.4389.72 (Offizieller Build) (64-Bit)
Firefox works fine 78.8.0esr (64-Bit)

**Comment by jlfwong** [comment]
Hi @TZanke!

Do you have a file that can reproduce this issue? It's difficult to make progress without that (though the call stack is helpful)

**Comment by TZanke** [comment]
Right now all my current examples are working, maybe this issue is already fixed. I will keep you updated if it occurs again.

**Comment by bogdandm** [comment]
I got same error in this file from py-spy. 
![image](https://user-images.githubusercontent.com/11839115/127883766-cf3d19f6-1a3a-44e6-acf6-407cc5f786e0.png)
[test.zip](https://github.com/jlfwong/speedscope/files/6917902/test.zip)

**Comment by bjorn3** [comment]
Just a (possibly irrelevant) observation: The max stack size in the profile is 186 frames. (`cat test.json | jq '.profiles[].samples[] | length' | sort -n | tail -n1`)
