### ISSUE TITLE
Showing line numbers in Sandwich view

### ISSUE THREAD

**Issue by philz** [jlfwong/speedscope#379]
Hi!

I love Speedscope. The profiles I look at (generated with Node; mostly in Chrome debugger format) tend to display in sandwich view with just function names but not line numbers. There are a lot of anonymous lambdas and methods that get implemented by subclasses, so it's a pain to figure out where the caller is.

Would Speedscope be open to showing line numbers in sandwich view? I may be able to give it a shot, but noticed that it was suggested to file an issue first.

Thanks.

**Comment by jlfwong** [comment]
Hi @philz!

Sorry for the very delayed response. This has been addressed in #365 and should go out with the next release.
