### ISSUE TITLE
Can I get more clarity on this error " Samples must be provided in increasing order of cumulative value."

### ISSUE THREAD

**Issue by justinsaunders** [jlfwong/speedscope#405]
I'm tracing code execution in my own project with manual instrumentation, and converting to speed scope format (0.0.1). However when I import to SpeedScope I get the following error:
 Samples must be provided in increasing order of cumulative value. Last sample was 62942451778, this sample was 62942451732

This constraint isn't mentioned in any of the docs discussing file format. Can anyone help me understand what this is telling me?

**Comment by tom93** [comment]
Probably not relevant to you any more, but as the docs do say:

> The "at" field of every event must be in non-decreasing order.

https://github.com/jlfwong/speedscope/blob/v1.14.0/src/lib/file-format-spec.ts#L79

I think this issue can be closed.
