### ISSUE TITLE
Callgrind import error

### ISSUE THREAD

**Issue by andryandrew** [jlfwong/speedscope#414]
I get an error importing a `Callgrind` profile obtained by profiling a python script.
JS console output:
```
(index.ts:173) Importing as Callgrind profile
(callgrind.ts:420) Ignoring assignment to unrecognized key "ob=(48) /home/[...]/lib/python3.9/site-packages/scipy/linalg/cython_lapack.cpython-39-x86_64-linux-gnu.so" on line 21
(callgrind.ts:420) Ignoring assignment to unrecognized key "cob=(2) /usr/lib/libc.so.6" on line 32
(application.tsx:179) Failed to load format Error: Unrecognized line "* 0 1" on line 37
    at n.parse (callgrind.ts:326:13)
    at r (callgrind.ts:517:58)
    at index.ts:174:34
    at Generator.next (<anonymous>)
    at s (index.ts:203:2)
```
I see `Callgrind` support has been merged but maybe it is still not officially supported?

**Comment by jlfwong** [comment]
Hi @andryandrew

Callgrind support is indeed merged. If you can provide the actual file failing to import (or a simplified version which fails to import into speedscope but imports correctly into kcachegrind or qcachegrind), that would be helpful for debugging this further.

**Comment by BotellaA** [comment]
@jlfwong any chance to have your feedback on this? 🙏

**Comment by jlfwong** [comment]
Hey, I'm looking it.

The subposition stuff is working, but there's something else weird going on with import.

Out of curiosity, how did you generate this file and how have you been able to visualize it outside of speedscope?

**Comment by jlfwong** [comment]
Thanks for the report @andryandrew and @BotellaA. The fix should be live on https://www.speedscope.app/ now
