### ISSUE TITLE
Chrome 114 profiler output change result in speedscope not rendering the stack trace anymore

### ISSUE THREAD

**Issue by shuhaowu** [jlfwong/speedscope#420]
I noticed the Chrome 114 has changed the profiler json output (also increased the size by a factor of 5-30 in some cases!). Loading the new format in speedscope results in speedscope not rendering the actual JavaScript stack trace, but something like this. I also noted there are multiple "tracks" now (whatever the top dropdown is basically):

![image](https://github.com/jlfwong/speedscope/assets/338100/7830662d-6189-4198-b6d4-e40dc5906152)

In 113 the normal flamegraph is shown... Not sure if this is a Chrome-side issue or a speedscope side problem right now.

I check all of the "Tracks" and the stack trace is no where to be found...

**Comment by jlfwong** [comment]
Ahhh thanks for the heads up. That's a huge bummer -- a fatal problem with building tools on proprietary file formats.

Not sure when I'll have time to look at this, but good to know.

If someone else would like to take a crack at this, https://github.com/jlfwong/speedscope/blob/main/src/import/chrome.ts is the code that deals with current versions of the chrome profile format.

On a chance guess, I'll bet they switched to using the trace event format described here: https://github.com/jlfwong/speedscope/blob/main/src/import/trace-event.ts

**Comment by shuhaowu** [comment]
Thanks for the quick response. It's a huge disappointment indeed. I use speedscope almost daily just for the merged flamegraph (left heavy) so I can see the hotspot of an application. I guess I can downgrade to 113 but it's a hassle. If I have some time I might look into this, but it's unclear if I'll have time.

Further, what was like a 10MB trace can be now like 400+MB. Just processing this file will be quite time and memory consuming...

**Comment by jlfwong** [comment]
Okay, I can repro the issue. I'll look into it

**Comment by jlfwong** [comment]
@shuhaowu Thanks for the report, the fix should be live on https://www.speedscope.app/ now!
