### ISSUE TITLE
[Question] How to see frame instances count

### ISSUE THREAD

**Issue by Goose97** [jlfwong/speedscope#436]
This is not a bug submission but rather a discussion/question.

Is there any way to know the instances count of a given frame. Currently, we only show the total/self time accross all instances. My use case is measuring how many times a function is invoked.

![image](https://github.com/jlfwong/speedscope/assets/35915460/c842f3eb-196b-4790-9d91-4fc193ec1a24)

**Comment by jlfwong** [comment]
There's no way at the moment. In the general case, it wouldn't make sense to have in the interface because many of the profile formats speedscope ingests are sampling profiles rather than instrumented profiles, so the data to answer that question doesn't exist in the profile output.
