### ISSUE TITLE
output for speedscope format is not loaded in Firefox in Ubuntu unless it has .json extension

### ISSUE THREAD

**Issue by undercover87** [jlfwong/speedscope#443]
ubuntu 22.04
firefox 116.03

if the output file is arbitrarily named (e.g. profile.speedscope) , Firefox in Ubuntu can't load it. For a "long" period of time it seems as it is loading something, but when the progress bar is completed, we see nothing on the screen. If I add a .json extension in the same file, then firefox in ubuntu renders it just fine and instantly.

The same file (with an arbitrary name) can be loaded succesfully using Chrome in windows (for instance). 

This should be documented more explicitly in the docs.

**Comment by jlfwong** [comment]
Hi @undercover87! Can you please provide a specific test file and open the developer tools console and see if there are errors there?

**Comment by undercover87** [comment]
Hello ,
well I said that is works when I add a json extension and it did work for one of the files, but it did not work on another.  This is the console output
`
speedscope v1.16.0 [speedscope.f27db165.js:187:123](https://www.speedscope.app/speedscope.f27db165.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [speedscope.f27db165.js:14:8659](https://www.speedscope.app/speedscope.f27db165.js)
WebGL initialized. renderer: llvmpipe, vendor: Mesa/X.org, version: WebGL 1.0 [speedscope.f27db165.js:30:1142](https://www.speedscope.app/speedscope.f27db165.js)
Source map error: Error: request failed with status 404
Resource URL: https://www.speedscope.app/speedscope.f27db165.js
Source Map URL: speedscope.f27db165.js.map

Source map error: Error: request failed with status 404
Resource URL: https://www.speedscope.app/reset.8c46b7a1.css
Source Map URL: reset.8c46b7a1.css.map

Uncaught Error: Expected reader.result to be an instance of ArrayBuffer
    t https://www.speedscope.app/import.8ae8aa3d.js:42
    t https://www.speedscope.app/import.8ae8aa3d.js:42
    fromFile https://www.speedscope.app/import.8ae8aa3d.js:42
    x https://www.speedscope.app/import.8ae8aa3d.js:121
    F https://www.speedscope.app/import.8ae8aa3d.js:121
    F https://www.speedscope.app/import.8ae8aa3d.js:121
    x https://www.speedscope.app/import.8ae8aa3d.js:121
    w https://www.speedscope.app/speedscope.f27db165.js:183
    n https://www.speedscope.app/speedscope.f27db165.js:183
    promise callback*l https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    w https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    loadProfile https://www.speedscope.app/speedscope.f27db165.js:183
    n https://www.speedscope.app/speedscope.f27db165.js:183
    promise callback*l https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    loadProfile https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    onFileSelect https://www.speedscope.app/speedscope.f27db165.js:183
    E https://www.speedscope.app/speedscope.f27db165.js:2
[import.8ae8aa3d.js:42:3912](https://www.speedscope.app/import.8ae8aa3d.js)
    t https://www.speedscope.app/import.8ae8aa3d.js:42
    (Async: EventListener.handleEvent)
    t https://www.speedscope.app/import.8ae8aa3d.js:42
    fromFile https://www.speedscope.app/import.8ae8aa3d.js:42
    x https://www.speedscope.app/import.8ae8aa3d.js:121
    next self-hosted:1376
    F https://www.speedscope.app/import.8ae8aa3d.js:121
    F https://www.speedscope.app/import.8ae8aa3d.js:121
    x https://www.speedscope.app/import.8ae8aa3d.js:121
    w https://www.speedscope.app/speedscope.f27db165.js:183
    next self-hosted:1376
    n https://www.speedscope.app/speedscope.f27db165.js:183
    (Async: promise callback)
    l https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    w https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    next self-hosted:1376
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    loadProfile https://www.speedscope.app/speedscope.f27db165.js:183
    next self-hosted:1376
    n https://www.speedscope.app/speedscope.f27db165.js:183
    (Async: promise callback)
    l https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    m https://www.speedscope.app/speedscope.f27db165.js:183
    loadProfile https://www.speedscope.app/speedscope.f27db165.js:183
    loadFromFile https://www.speedscope.app/speedscope.f27db165.js:183
    onFileSelect https://www.speedscope.app/speedscope.f27db165.js:183
    E https://www.speedscope.app/speedscope.f27db165.js:2
Source map error: Error: request failed with status 404
Resource URL: https://www.speedscope.app/import.8ae8aa3d.js
Source Map URL: import.8ae8aa3d.js.map
`

**Comment by jlfwong** [comment]
Thanks for providing the stack trace! That's helpful, but still very difficult to debug without an actual test file that failed import.

Can you please upload the profile that's failing to import?

The other thing that would be helpful to know is where the file came from. Was it an export from speedscope itself, or did it come from another tool that was output in speedscope format?

**Comment by undercover87** [comment]
Hello, unfortunately I can't provide the whole profile file, could you maybe me point me to a specific portion of the profile file you'd like to see based on the stack output? 
The output file came from pyspy.

**Comment by jlfwong** [comment]
Realistically, I won't be able to investigate the problem unless I can reproduce it myself. If you can produce another file using pyspy on a codebase other than yours which contains none of the proprietary information, I should be able to investigate

**Comment by KerekesDavid** [comment]
I just ran into the same problem, and I manage to reproduce it.

The file I was reading was created by running the debugger with sudo, and therefore the file is inacessible to the browser. Trying to import it under both Firefox and Chrome just makes speedscope hang. Changing file permissions so the file is readable fixes the problem. (Which is why renaming or moving the file to Windows solved the issue for OP)

Reproduction steps:
1. `sudo chown root example.json`
2. Speedscope in Firefox hangs with the above error.
[example.json](https://github.com/jlfwong/speedscope/files/13460502/example.json)

**Comment by jlfwong** [comment]
@undercover87 Can you check file permissions for your reproduction case and see if that's the issue? Asking because that would suggest a different problem than described in the OP description

**Comment by undercover87** [comment]
Thanks @KerekesDavid , this solved the issue indeed!

**Comment by KerekesDavid** [comment]
Not sure if you should close this issue, I imagine a lot of people will run into this problem. If possible, it might be prudent to give the user a useful error message instead of hanging. @jlfwong

**Comment by jlfwong** [comment]
@KerekesDavid If there's a way to detect this specific problem (by e.g. catching the error and warning that it may be caused by this then re-throwing), I'd accept a PR to address that!

**Comment by undercover87** [comment]
I can take a look and let you know if I can handle it.
