### ISSUE TITLE
Cannot zoom 100% vertically

### ISSUE THREAD

**Issue by naftaly** [jlfwong/speedscope#482]
You can easily zoom horizontally, but it's not possible to fill the screen vertically.

**Comment by jlfwong** [comment]
Hi @naftaly! This is by design -- can you explain what your use case is? You can zoom out the entire interface using browser zoom (switch to the URL bar and hit cmd/ctrl-+)

**Comment by naftaly** [comment]
I’ll have to try the browser zoom with the tool. It just seems like I should be able to adjust the zoom rectangle in the track to show everything, no special use case other than simply using the tool and expecting to to be possible.

**Comment by jlfwong** [comment]
Gotcha -- I'm going to close this for now since this is expected behavior
