### ISSUE TITLE
Java profiling example

### ISSUE THREAD

**Issue by edmcman** [jlfwong/speedscope#485]
A very easy way to trace Java programs is using [async-profiler](https://github.com/async-profiler/async-profiler)

Importing from async-profiler:
* ./asprof start Ghidra # (assuming you want to profile Ghidra)
* ./asprof stop -o collapsed -f /tmp/prof.collapsed Ghidra # when finished
* Open prof.collapsed in SpeedScope

It would be great to see this in the wiki

**Comment by jlfwong** [comment]
Hi @edmcman!

Happy to add a page to the wiki if you can write the markdown in the same format as existing page like this: https://github.com/jlfwong/speedscope/wiki/Importing-from-.NET-Core

**Comment by edmcman** [comment]
Awesome, how is this?

https://gist.github.com/edmcman/ffd64020aeefba90df459b39dba15a20

**Comment by jlfwong** [comment]
@edmcman done! thanks for the contribution!

Added to README: https://github.com/jlfwong/speedscope/commit/146477a8508a6d2da697cb0ea0a426ba81b3e8dc
https://github.com/jlfwong/speedscope/wiki/Importing-from-async%E2%80%90profiler-(Java)
