### ISSUE TITLE
Format Support: Import from go pprof

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#60]
There is Google protobuf-based file format used for profilers in Google tooling, and is more specifically used by `go tool pprof`.

https://github.com/google/pprof/tree/master/proto
https://blog.golang.org/profiling-go-programs

**Comment by jlfwong** [comment]
I’ll commit to implementing this feature myself if a total of $200 of donations is made to any combination of these specific charities:

- [American Civil Liberties Union](https://www.aclu.org/)
- [/dev/color](https://www.devcolor.org/welcome): /dev/color is a non-profit organization whose mission is to empower Black software engineers to help one another grow into industry leaders.
- [Girls Who Code](https://girlswhocode.com/about-us/): Girls Who Code was founded with a single mission: to close the gender gap in technology

If you’d like to contribute to that total, please post a screenshot of your donation receipt in this thread*.

Independent of that, I would accept a PR to implement this, regardless of donation amounts.

*: I'm planning on trying this policy on a number of issues. Donations will apply to the total of exactly one issue, so please don't post the same receipt in multiple issue threads.

**Comment by davecheney** [comment]
![f9ebb2c3-5162-4ffc-ba61-97a5dc4456c6](https://user-images.githubusercontent.com/7171/45591429-0f6f8580-b996-11e8-9341-07c9cf2bdb51.png)

Half way there.

**Comment by jmoiron** [comment]
![](http://jmoiron.net/i/1yh2h7m.png)

**Comment by jlfwong** [comment]
The work in progress PR to implement this can be found in #165 if you'd like to follow along

**Comment by jlfwong** [comment]
@jmoiron @davecheney This should now be complete! See import instructions here: https://github.com/jlfwong/speedscope/wiki/Importing-from-pprof-(go). The support has been deployed to the website and also published to npm.

2 caveats:

1. The go profiler seems to only record aggregate information, and not historical information. What this means in practice, I think, is that the time order view may end up being very similar to the left heavy view.
2. https://golang.org/pkg/net/http/pprof/ exposes an interface to download trace files (e.g. http://localhost:6060/debug/pprof/trace?seconds=5), which are not currently supported. This issue was specifically for importing go pprof files. If you'd like to have access to the information in the trace files too, please see #77.
3. If profiles do not contain symbols, speedscope cannot automatically symbolicate them because it doesn't have access to the binaries (and also because that would probably be really complicated). The profiles I tested locally seemed to all have the symbol information in them.

I have done very little go programming, so I'm not totally sure if I've understood the requirements entirely here, but it does seem like go profiles are importing in a way that truthfully reproduces the contents of the profile files.
