### ISSUE TITLE
Instruments .trace files do not load in speedscope.app

### ISSUE THREAD

**Issue by uber-mahyar2** [jlfwong/speedscope#63]
When trying to open an instruments time tracing trace, speedscope fails to load it with an error.  Pasting in a deep copy of the same trace works.  The error that shows up in the JS console is just 'undefined'

Here is an example trace that fails. I created it by tracing xcode 9.4 for a few seconds.
[xcode.trace.zip](https://github.com/jlfwong/speedscope/files/2116708/xcode.trace.zip)

**Comment by jlfwong** [comment]
Hi @uber-mahyar2! Thanks for filing a bug with a reproduction case! I'll try to investigate sometime in the next few days

**Comment by rudro** [comment]
So from your post, it seems the `scheme.xml` files you saw were ascii text files.  However, if I try the same thing as Mahyar, I see this :

```
$ find . -name schema.xml -exec file {} +
./corespace/run1/core/stores/indexed-store-14/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-13/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-12/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-15/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-5/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-2/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-3/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-4/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-10/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-16/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-11/schema.xml: zlib compressed data
./corespace/run1/core/stores/indexed-store-8/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-1/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-6/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-7/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-0/schema.xml:  zlib compressed data
./corespace/run1/core/stores/indexed-store-9/schema.xml:  zlib compressed data
```

If you're code (I haven't looked) assumes there are plain text, then this would be one of the issues with opening that trace file.

**Comment by uber-mahyar2** [comment]
In this xcode.trace xml case although, they are ASCII text:
```
$ find . -name schema.xml -exec file {} +
./corespace/run1/core/stores/indexed-store-5/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-2/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-3/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-4/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-1/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-6/schema.xml: ASCII text
./corespace/run1/core/stores/indexed-store-0/schema.xml: ASCII text
```

**Comment by jlfwong** [comment]
> If your code (I haven't looked) assumes these are plain text, then this would be one of the issues with opening that trace file.

Haha, yeah, I glossed over that in the blogpost. In Instruments 8 they were plaintext, but in Instruments 9 they're zip files. I take that into account when loading profiles.

https://github.com/jlfwong/speedscope/blob/7846cce806aa92758d5e1753bfde0acec8ad8d25/import/instruments.ts#L197-L236

**Comment by jlfwong** [comment]
@uber-mahyar2 The testfile you provided was really helpful in diagnosing this!

The fixed version should now be live on https://www.speedscope.app

**Comment by uber-mahyar2** [comment]
Wow that was really fast, thank you!

**Comment by uber-mahyar2** [comment]
Just as an FYI, the same `undefined` error shows up still when opening in Safari Version 11.1.1 (13605.2.8).  I don't know how much a priority safari is although. 

Still thank you very much for doing this!

**Comment by jlfwong** [comment]
At the moment, only Firefox & Chrome are supported. I haven't been testing much in Safari, an I suspect many things are broken
