### ISSUE TITLE
Instruments import only provides access to the last run

### ISSUE THREAD

**Issue by uber-mahyar2** [jlfwong/speedscope#66]
If you do multiple runs of a trace, it seems like speed scope only renders the last run?   Or kind of merges them together?  It's kind of hard to tell.

Here is an example trace on safari.

Maybe a run selector needs to be added?

[2-run-safari-instruments-v9.trace.zip](https://github.com/jlfwong/speedscope/files/2120415/2-run-safari-instruments-v9.trace.zip)

**Comment by jlfwong** [comment]
Yeah, there's a bunch of trickiness here.

1. The instruments trace import only visualizes the last run
2. Each run only visualizes the main thread

It would be great to fix both of those things, and they may need different solutions

**Comment by uber-mahyar2** [comment]
When I was trying to make a good example file for this ticket, I created an instruments file that doesn't render at all.  Barely any spans are running since the safari app is fairly idle.  There are also 2 runs.   I was also using instruments v10.  When I create a single run v10 instruments file although, it does render properly with speedscope.

https://uber.box.com/s/hfboka3vmnvxfn8da30r4fnnjwk9m7kh

**Comment by jlfwong** [comment]
Thanks for the test file! I haven't tested with Instruments 10 at all -- when was that released?

**Comment by uber-mahyar2** [comment]
It was released at WWDC as part of the xcode 10 beta.  You will need an apple developer account to download it , but I think the free account can do it.   Figma has iOS apps on the app store, so your apple account with figma should definitely be able to download the dmg for you.

https://developer.apple.com/xcode/  <- tap the blue download button in the top right

Here is an example one run instruments v10 looking at itunes: https://uber.box.com/s/vk4h1nisc8okb4b2a4qzamns5x0nk19l
