### ISSUE TITLE
Support import of multithreaded/multiprocess profiles

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#82]
This will be helpful for supporting both multiprocess/multithread Instruments import (#63) and general trace import (#77)

This is required for #31.

Here's a rough toolbar mockup showing navigation controls between the profiles from different threads/processes.
![image](https://user-images.githubusercontent.com/150329/43683072-7d4ead20-9839-11e8-90b7-b440071cd234.png)

**Comment by uber-mahyar2** [comment]
Generalizing this as multitrack support would be smart.  Coworkers have talked about wanting to add a separate manual span track (like instruments POIs) on top of the normal main thread track.
