### ISSUE TITLE
Better main thread detection during Instruments data import.

### ISSUE THREAD

**Issue by rudro** [jlfwong/speedscope#91]
For a complex, heavily multi-threaded app, the logic that assumes that the thread with the most samples is the main thread can be mislead.

Sadly, I don't have a concrete suggestion for something better. I notice that main appears to usually be thread id '4', but there has to be something less hacky.

Just wanted to open this issues to start a discussion about this.

**Comment by jlfwong** [comment]
@rudro Would this still be important to solve if speedscope supported importing profiles w/ multiple threads & processes? (See #82)

**Comment by jlfwong** [comment]
@rudro When you drop an instruments trace onto https://www.speedscope.app/, it should now import all threads in all runs. If you get a chance to give it a try, please let me know how it works for you!

**Comment by rudro** [comment]
Tried this out, works great! Thanks.

**Comment by jlfwong** [comment]
@rudro Hey I'm writing a blogpost for the release of speedscope 1.0. Any chance you'd be able to share some information about what you've been using this for? It sounds like you've been using this predominately through Instruements. Is it for iOS profiling? Is speedscope being used at Uber?
